ALTER TABLE terrains
ADD COLUMN IF NOT EXISTS environment_benefits JSONB DEFAULT '[]',
ADD COLUMN IF NOT EXISTS trust_items JSONB DEFAULT '[]',
ADD COLUMN IF NOT EXISTS agency_name TEXT,
ADD COLUMN IF NOT EXISTS notary_name TEXT,
ADD COLUMN IF NOT EXISTS notary_phone TEXT,
ADD COLUMN IF NOT EXISTS ninacad TEXT;

ALTER TABLE terrains
ADD COLUMN IF NOT EXISTS catalog_tags JSONB DEFAULT '[]',
ADD COLUMN IF NOT EXISTS terrain_use TEXT,
ADD COLUMN IF NOT EXISTS catalog_bucket TEXT,
ADD COLUMN IF NOT EXISTS display_in_discovery BOOLEAN DEFAULT false;